name: mds-approximations
channels:
- qiime2
- conda-forge
- defaults
- bioconda
- biocore
dependencies:
- scikit-bio
- click
- numpy
- scikit-learn
- scipy
- pandas
- jupyter
- matplotlib
- python=3.7