#!/usr/bin/env python

import click
from skbio import OrdinationResults, DistanceMatrix

from mdsa.kruskal_stress import KruskalStress


@click.command()
@click.argument('distance_matrix_path',
                type=click.Path(exists=True, dir_okay=False, readable=True))
@click.option('--ordination_results_path',
              type=click.Path(exists=True, dir_okay=False, readable=True),
              help='Reference OrdinationResults to compare against')
@click.option('--outpath', type=click.Path(dir_okay=False, writable=True))
def main(distance_matrix_path, ordination_results_path, outpath):
    """
    Arguments:
    input: path to serialized DistanceMatrix file

    """

    click.echo('Calculating kruskal stress, comparing {} to {}'.format(
        distance_matrix_path, ordination_results_path
    ))
    distance_matrix = DistanceMatrix.read(distance_matrix_path).data
    ordination_results = OrdinationResults.read(
        ordination_results_path).samples.as_matrix()

    kruskal_stress = KruskalStress(distance_matrix,
                                   ordination_results).calc_kruskal_stress()

    click.echo('Outputting kruskal results to {}'.format(outpath))
    # Write kruskal stress output to file
    with open(outpath, 'w') as f:
        f.write(str(kruskal_stress))


if __name__ == '__main__':
    main()
