#!/usr/bin/env python

import click
from skbio import OrdinationResults, DistanceMatrix

from mdsa.kruskal_stress import KruskalStress


@click.command()
@click.argument('input',
                type=click.Path(exists=True, dir_okay=False, readable=True))
@click.option('--reference',
              type=click.Path(exists=True, dir_okay=False, readable=True),
              help='Reference OrdinationResults to compare against')
@click.option('--outpath', type=click.Path(dir_okay=False, writable=True))
def main(input, reference, outpath):
    """
    Arguments:
    input: path to serialized DistanceMatrix file

    """

    click.echo('Calculating kruskal stress, comparing {} to {}'.format(
        input, reference
    ))
    inp = DistanceMatrix.read(input).data
    ref = OrdinationResults.read(reference).samples.as_matrix()

    kruskal_stress = KruskalStress(ref, inp).calc_kruskal_stress()

    click.echo('Outputting kruskal results to {}'.format(outpath))
    # Write kruskal stress output to file
    with open(outpath, 'w') as f:
        f.write(str(kruskal_stress))


if __name__ == '__main__':
    main()
